# version: '3'
services:
  redis:
    image: redis:7.2-alpine
    container_name: redis-memory
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

volumes:
  redis_data:
